---

- hosts: bluemix
  roles:
    - role: apache
      apache_modules:
        - rewrite
        - proxy
        - proxy_http
        - proxy_fcgi
      apache_user: www-data
      apache_group: www-data
      apache_log_dir: /data/logs/apache2
      apache_logrotate_frequency: weekly
      apache_logrotate_count: 52
      apache_ports:
        - 80
      apache_secure_frame: false
      apache_vhosts: "{{bluemix_vhosts}}"
      tags: apache
    - role: dev-common
      env: bluemix
    - role: cloudfoundry
